DynaSim/DynaSim

functions/ApplyModifications.m, functions/CheckCovary.m, functions/PlotData.m, functions/Vary2Modifications.m
=> Issue 52 - covary two mechanisms

demos/dsDemos_PlotData2.m
=> Fix regexes in demo

functions/dsImport.m
Resolved: importing data from batch with only one simulation
Edited dsImport: moved modifications=sim_info... to before conditional to add tmp_data.varied and added "&& ~isempty(modifications)"
=> Resolved: importing data from batch with only one simulation

functions/internal/dsWriteDynaSimSolver.m
Resolved Issue #209
1. Updated state variable indexing in conditional check to use _last for current time step
2. Removed undesired preallocation of _last for the spike time matrix
=> Iss209: enables monitoring spikes while doing real-time downsampling

functions/internal/dsClassifyEquation.m
This properly fixes issue #234 both in matlab and octave. 
Jason please review and test the proposed solution...
=> proper fix for issue 234

functions/dsSimulate.m, functions/internal/dsCreateBatch.m, functions/internal/dsStudyinfoIO.m, functions/internal/dsUpdateStudy.m, functions/internal/dsWriteDynaSimSolver.m, functions/internal/dsWriteMatlabSolver.m
=> saving all mat files as -v7 for compatibility (except simulated data that is more sophisticated than this)

demos/dsDemos.m, functions/dependencies/plot2svg.m, functions/dsAnalyze.m, functions/internal/dsCreateBatch.m, functions/internal/dsExportData.m, functions/internal/dsStudyinfoIO.m, functions/internal/dsUpdateStudy.m, functions/internal/qsub_job, functions/internal/qsub_jobs_loop
Fixed bugs of reverted merge issue #249
=> qjobs loop update and bunch of fixes for octave cluster compatibility

demos/dsDemos.m
=> added example of 'matCompatibility_flag' use in dsDemos

functions/internal/dsLocateModelFiles.m
=> Fix #262 dsLocateModelFiles optimize and fix bugs

functions/internal/dsGenerateModel.m, functions/internal/dsWriteDynaSimSolver.m
This pull request resolves Issue #264 by adding support for handling multidimensional pops in dsGenerateModel and dsWriteDynaSimSolver. The latter was modified to initialize state variables using (n,m,t) then state variable dimensions are shifted after simulation back to (t,n,m).
=> Iss264 2d pops

functions/internal/dsCheckSpecification.m, functions/internal/dsGenerateModel.m, functions/internal/dsParseModelEquations.m, functions/internal/dsPlot2D.m
Handle exceptional cases for 2D pops (Issue #264):
- Pop sizes in equations: dv[n,m]/dt
=> Iss264 2 d pops

functions/dependencies/eksr.m
eksr.m (Epanechnikov Kernel smoothing regression) works better than ksr.m (Gaussian Kernel smoothing regression)
=> adding eksr.m to functions/dependencies

functions/internal/dsWriteDynaSimSolver.m
applying the same patch to dev branch
=> fix for issue #277

functions/dynasim.m
=> set GUI size to full screen

functions/dynasim.m
=> added batch manager for parameter sweeps

functions/internal/dsParseModelEquations.m, functions/internal/dsWriteDynaSimSolver.m
Issue mostly resolved in Pull Request 
% Supported:
% - monitor VAR.spikes(#)
% - monitor VAR.spikes(thresh)
% - monitor VAR.spikes(thresh,#)
% - monitor VAR.spikes(#,#)
TODO: support: monitor VAR.spikes(thresh,buffer_size)
=> Iss304 spike buffer size

functions/internal/dsApplyModifications.m, functions/internal/dsCombineSpecifications.m, functions/internal/dsImportModel.m
This implements the "simple approach" described in Issue #246 
Its use is documented in the example on connecting two network models.
=> Iss246 combine networks

functions/dsSimulate.m, functions/internal/dsCreateBatch.m, functions/internal/qsub_job, functions/internal/qsub_jobs_array, functions/internal/qsub_jobs_array_one_file, functions/internal/qsub_jobs_loop
fixed parfor with loop and array modes, octave with array mode, and made array mode mirror loop mode interface
=> fix par and array mode

functions/internal/dsCreateBatch.m
make profile related to $JOB_ID
=> fix error with profile

functions/dsAnalyze.m, functions/dsSimulate.m, functions/internal/dsCreateBatch.m
=> Revert "replaced all instances of 'parallel_flag' by 'parfor_flag'"

functions/dsAnalyze.m, functions/dsSimulate.m, functions/internal/dsCreateBatch.m
Ooops reverting the revert: 
Reverts DynaSim/DynaSim#352
=> Revert "Revert "replaced all instances of 'parallel_flag' by 'parfor_flag'""

functions/dynasim.m
=> remove subplot xdata ydata call

functions/dsSimulate.m, functions/internal/dsApplyModifications.m, functions/internal/dsVprintf.m, functions/internal/dsWriteDynaSimSolver.m, functions/internal/dsWriteMatlabSolver.m
=> Iss375 1filemode dot

functions/dependencies/plot2svg.m, functions/dsAnalyze.m, functions/dsImport.m, functions/dsPlot2.m, functions/dsSimulate.m, functions/internal/dsCreateBatch.m, functions/internal/dsExportData.m, functions/internal/dsSetupStudy.m, functions/internal/dsStudyinfoIO.m
=> Iss378 analyze

functions/dsImport.m, functions/internal/dsImportResults.m, functions/internal/dsNameFromVaried.m, functions/internal/dsStudyinfoIO.m
=> Iss385 posthoc results

functions/dsAnalyze.m
=> fix iss #396

functions/dsAnalyze.m, functions/dsImport.m, functions/dsPlot.m, functions/internal/dsApplyModifications.m, functions/internal/dsImportResults.m, functions/internal/dsWriteDynaSimSolver.m, functions/internal/dsWriteMatlabSolver.m
it would change flag to save results if no output. but has not output if
no save result flag in dsSim. so now checks for if in sim before
changing the flag. also switched back to try catch.
=> fix #397 bug dsSim with no result save

functions/dependencies/ear/tight_subplot2.m
=> attempt to fix #437

functions/internal/dsWriteDynaSimSolver.m
initiliazing the variables to empty arrays fixes the issue
=> fix for issue #454 (LIF model error)

functions/dsAnalyze.m
Definitely overkill, but practicing the workflow.
=> dsAnalyze: commenting out '& isfield(result, 'time')' on line 893.

functions/internal/dsGenerateModel.m
Same as #577 which was closed and couldn't be reopen
=> Adding access to all state variables, not just the first

functions/internal/dsGenerateModel.m
This fixes the reason #580 increased the time it took to generate a model so dramatically.
=> Fix for stvar lines not being excluded

functions/internal/dsClassifyEquation.m
Not sure why it didn't prompt issues w/o whitespace, when I tested previous commit (pull request #590 ), but anyways, making it right this time
=> fixing previous pull request

functions/internal/dsGenerateModel.m, functions/internal/dsParseModelEquations.m, functions/internal/dsPropagateFunctions.m, functions/internal/dsPropagateNamespaces.m, functions/internal/dsPropagateParameters.m, functions/internal/dsWriteDynaSimSolver.m
Reverts DynaSim/DynaSim#593
Found an issue in the LIF model.
I'm close to fix it but not quite yet there...
=> Reverting because of faulty behavior for the LIF model

functions/internal/dsParseModelEquations.m
This is particularly important for complex stimulation protocols:
Column vectors contain stimulus-dependent information: times for onset-offset (including overlapping ones if wanted), stimulus strengths, stimulus centers, etc.
This way one can specify a number of stimuli and process all them at once (summing over the first dimension). 
All this is applied in a vectorized manner for all neurons across the population (second dimension).
=> allow passing parameters as column vectors

functions/internal/dsClassifyEquation.m, functions/internal/dsCompareSolveFiles.m, functions/internal/dsParseModelEquations.m, functions/internal/dsWriteDynaSimSolver.m
Parameter arrays are great, overall in the context of #596 
Unfortunately I could not find a way to make them work with the Matlab Coder :(
=> Added parameter arrays, fixed mex crash and removed repeated rng calls

functions/internal/dsCheckSpecification.m
=> List multiple connections in one connection element (e.g., (A,B)->C)

functions/internal/dsGenerateModel.m
@jsherfey this commit fixes my issue, please review
=> fixes #641

functions/internal/dsGenerateModel.m, functions/internal/dsParseModelEquations.m
This allows monitoring functions with linker arguments
=> Fixes #490

functions/dependencies/Coverage/Coverage/src/+edu/+stanford/+covert/+test/Coverage.m, functions/dependencies/DataHash_20160618/DataHash.m, functions/dependencies/compareFigFiles/compareFigFiles.m, functions/dependencies/compareFigFiles/compareFigFiles2.m, functions/dependencies/compareFigFiles/compareFigFiles_original.m, functions/dependencies/ear/fileparts2.m, functions/dependencies/m2html/m2html.m, functions/dependencies/m2html/mwizard.m, functions/dependencies/m2html/mwizard2.m, functions/dsAnalyze.m, functions/dsImport.m, functions/dsSimulate.m, functions/dynasim.m, functions/internal/dsCheckStudyinfo.m, functions/internal/dsCreateBatch.m, functions/internal/dsGetSolveFile.m, functions/internal/dsImportPlots.m, functions/internal/dsImportResults.m, functions/internal/dsIsDevMode.m, functions/internal/dsMergeResults.m, functions/internal/dsSetupStudy.m, functions/internal/dsStudyinfoIO.m, functions/internal/dsUpdateStudy.m, functions/internal/dsWriteDynaSimSolver.m
- same dynasim solve files for matlab/octave (including how monitors and rng are managed)
- changed name and set `sim_log_flag` to 0 by default
- replaced instances of `isdir` to `isfolder` as recommended
- other cosmetic changes
=> Multiple changes

functions/dynasim.m
This is useful to run the DynaSim GUI directly from the terminal using Octave
=> adding an async_flag to the DynaSim GUI
